"""Machine-inspectable Public V1 API manifest.

This allowlist is the Release 1 support contract.  Importability elsewhere in
the repository does not make a symbol public.  Categories are disjoint by
fully-qualified ``(module, symbol)`` identity.
"""

from __future__ import annotations

from typing import Final


PUBLIC_V1_MANIFEST: Final[dict[str, object]] = {
    "schema": "engcore.public_v1_manifest/1",
    "distribution": {
        "name": "engineering-ai-core",
        "version": "1.0.0",
        "requires_python": ">=3.11",
        "status": "release-1-preparation",
    },
    "categories": {
        "scientific_core": {
            "engcore": ("__version__",),
            "engcore.release1_api": ("PUBLIC_V1_MANIFEST",),
            "engcore.scientific": (
                "SCIENTIFIC_CORE_VERSION",
                "ScientificCoreError",
                "InvalidScientificProblem",
                "UnitCompatibilityError",
                "ModelNotFoundError",
                "ModelValidityError",
                "SolverNotFoundError",
                "AmbiguousSolverError",
                "DuplicateRegistrationError",
                "ScientificValidationError",
                "Quantity",
                "coerce_quantity",
                "dimensionality",
                "normalize_unit",
                "ScientificProblem",
                "ScientificVariable",
                "ScientificParameter",
                "VariableKind",
                "VariableRole",
                "ScientificValue",
                "ValueKind",
                "IntegerValue",
                "BooleanValue",
                "CategoricalValue",
                "encode_value",
                "decode_value",
                "value_kind",
                "ObjectiveDefinition",
                "ObjectiveDirection",
                "ConstraintDefinition",
                "ConstraintOperator",
                "ConstraintCheck",
                "InitialCondition",
                "BoundaryCondition",
                "BoundaryKind",
                "ModelReference",
                "UncertaintySpecification",
                "UncertaintyRequirement",
                "ScientificModelDefinition",
                "ModelInputSpec",
                "ModelOutputSpec",
                "ModelBindingReport",
                "BindingIssue",
                "BindingIssueKind",
                "InputSourceKind",
                "ModelType",
                "ModelValidationStatus",
                "ModelRegistry",
                "ValidityDomain",
                "ValidityStatus",
                "ValidityAssessment",
                "RangeCondition",
                "CategoryCondition",
                "FlagCondition",
                "ScientificSolver",
                "SolverIdentity",
                "SolverSettings",
                "SolverCapability",
                "CoreCapabilities",
                "SolverRegistry",
                "PreparedSolve",
                "RawSolverOutput",
                "ConvergenceState",
                "ScientificResult",
                "ValidationReport",
                "ValidationCheck",
                "ValidationOutcome",
                "ValidationLevel",
                "unverified_report",
                "Uncertainty",
                "UncertaintyKind",
                "ProvenanceRecord",
                "to_json",
            ),
        },
        "lab_v1": {
            "engcore.scientific": (
                "ScientificTwin",
                "TwinDatum",
                "TwinDatumRole",
                "TwinKind",
                "TwinReference",
                "ScientificExperiment",
                "ExperimentBudget",
                "ScientificEvaluation",
                "EvaluationStatus",
                "OptimizerAdapter",
                "CandidateCodec",
                "ObjectiveEncoder",
                "NumericSearchBackend",
            ),
            "engcore.design": (
                "GENERATION_BINDING_METADATA_KEY",
                "CandidateGenerationBatch",
                "CandidateGenerationPlan",
                "CandidateProposal",
                "DesignCandidate",
                "DesignCandidateReference",
                "DesignEvaluation",
                "DesignEvaluationReference",
                "DesignPopulation",
                "DesignSpace",
                "DesignSpaceReference",
                "FidelityLadder",
                "FidelityRung",
                "FidelitySelection",
                "GenerationStrategy",
                "MixedVariableSampler",
                "ParetoArchive",
                "ProjectedObjective",
                "ProposalDecision",
                "ProposalGate",
                "ProposalRejection",
                "ResultBinding",
                "ScopedEliteArchive",
                "SelectionEligibility",
                "TwinMaterializer",
                "assignment_digest",
                "bind_generation_to_twin",
                "dominates",
                "generate_initial_population",
                "generation_binding_payload",
                "project_objectives",
                "require_result_binding",
                "validate_generation_binding",
                "validate_twin_generation_binding",
            ),
        },
        "mind_v1": {
            "engcore.design": (
                "AssessmentContext",
                "DesignMemoryEntry",
                "DesignMemoryLayerA",
                "DesignMemoryPolicy",
                "DesignMemoryRecord",
                "DesignMemoryScope",
                "EntryClassification",
                "ExplicitRetention",
                "RetentionReason",
                "classify_memory",
                "compare_entries",
                "merge_layer_a_records",
                "pareto_member_identities",
                "reason_overlaps",
                "verify_layer_a_attribution",
            ),
        },
        "proven_domains_and_systems": {
            "engcore.domains.electrical.dc": (
                "DCCircuit",
                "ElectricalNode",
                "Resistor",
                "DCVoltageSource",
                "DCCurrentSource",
                "PreparedDCSystem",
                "assemble",
                "CANONICAL_SCHEMA",
                "DOMAIN_ARTIFACT_TYPE",
                "CircuitBindingError",
                "DC_MODELS",
                "RESISTOR_OHM_MODEL",
                "KCL_MODEL",
                "IDEAL_VOLTAGE_SOURCE_MODEL",
                "IDEAL_CURRENT_SOURCE_MODEL",
                "models_for_circuit",
                "assumptions_for_models",
                "ELECTRICAL_DC_LINEAR",
                "build_dc_model_registry",
                "dc_solver_capabilities",
                "build_dc_problem",
                "verify_problem_matches_circuit",
                "problem_fingerprint",
                "resistor_relation_problem",
                "voltage_source_relation_problem",
                "ElectricalDCSolver",
                "ElectricalDCError",
                "solve_circuit",
                "DCValidationSettings",
                "build_validation_report",
            ),
            "engcore.domains.thermal.conduction1d": (
                "ConductionSlab",
                "SlabDiscretization",
                "build_conduction_problem",
                "CONDUCTION_MODELS",
                "DIFFUSION_MODEL",
                "THERMAL_CONDUCTION_1D",
                "Conduction1DSolver",
                "solve_slab",
                "SOLVER_ID",
                "SOLVER_VERSION",
                "BACKEND",
                "decay_factor",
                "exact_field",
                "exact_midpoint",
                "run_verification_gate",
                "VerificationReport",
                "RefinementRung",
                "VERIFICATION_LADDER",
                "ANALYTIC_REL_TOL",
                "CONVERGENCE_MIN_CONTRACTION",
                "MIN_RUNGS",
                "ConductionValidationSettings",
                "MIDPOINT_METRIC",
                "MAX_METRIC",
                "LEFT_METRIC",
                "RIGHT_METRIC",
                "FIELD_UNIT",
                "LENGTH_UNIT",
                "TIME_UNIT",
                "DIFFUSIVITY_UNIT",
                "ThermalConduction1DError",
                "SlabConfigurationError",
                "SlabBindingError",
            ),
            "engcore.domains.kinetics.cstr": (
                "ReactorChemistry",
                "ReactorOperation",
                "IntegrationSettings",
                "ReactorRun",
                "build_cstr_problem",
                "CSTR_MODEL",
                "CSTR_MODELS",
                "KINETICS_CSTR_NONISOTHERMAL",
                "CSTRSolver",
                "solve_reactor",
                "solve_reactor_bundle",
                "VerificationSolveBundle",
                "TransientTrajectorySample",
                "SOLVER_ID",
                "SOLVER_VERSION",
                "BACKEND",
                "steady_states",
                "steady_state_residual",
                "SteadyState",
                "arrhenius_rate_constant",
                "adiabatic_invariant_exact",
                "invariant_value",
                "invariant_is_exact",
                "STEADY_STATE_REFERENCE_ID",
                "STEADY_STATE_EXPRESSION",
                "INVARIANT_REFERENCE_ID",
                "INVARIANT_EXPRESSION",
                "run_verification_gate",
                "CSTRVerificationReport",
                "ToleranceRung",
                "TOLERANCE_LADDER",
                "TOLERANCE_REL_TOL",
                "INVARIANT_REL_TOL",
                "STEADY_STATE_REL_TOL",
                "STATIONARITY_REL_TOL",
                "CONVERGENCE_QOIS",
                "MIN_RUNGS",
                "CSTRValidationSettings",
                "measure_stiffness",
                "StiffnessMeasurement",
                "CA_FINAL_METRIC",
                "T_FINAL_METRIC",
                "T_MAX_METRIC",
                "T_AT_MAX_METRIC",
                "CONVERSION_METRIC",
                "METRIC_UNITS",
                "CONCENTRATION_UNIT",
                "TEMPERATURE_UNIT",
                "TIME_UNIT",
                "VOLUME_UNIT",
                "FLOW_UNIT",
                "RATE_CONSTANT_UNIT",
                "MOLAR_ENERGY_UNIT",
                "DENSITY_UNIT",
                "HEAT_CAPACITY_UNIT",
                "UA_UNIT",
                "DIMENSIONLESS",
                "MOLAR_GAS_CONSTANT",
                "MIN_VALID_TEMPERATURE_K",
                "MAX_VALID_TEMPERATURE_K",
                "KineticsCSTRError",
                "ReactorConfigurationError",
                "ReactorBindingError",
                "IntegrationBudgetExceeded",
            ),
            "engcore.domains.fluids.aerodynamics": (
                "disk_loading",
                "ideal_induced_hover_power",
            ),
            "engcore.systems.aerospace.multirotor": (
                "MULTIROTOR_CONSTRAINT_REF",
                "MultirotorProposalGate",
                "MultirotorReferenceRun",
                "MultirotorTargetAssessment",
                "MultirotorTargetSpec",
                "MultirotorTwinMaterializer",
                "build_reference_design_space",
                "evaluate_reference_candidate",
                "run_reference_study",
            ),
        },
    },
}


EXPERIMENT_ONLY_MODULES: Final[tuple[str, ...]] = (
    "engcore.design.d4_recombination",
    "engcore.design.d5_generation",
    "engcore.design.d6_next_experiment",
    "experiments.design_d7",
)

EXPERIMENT_ONLY_SYMBOLS: Final[frozenset[str]] = frozenset(
    {
        "CHILD_GENERATION",
        "COMPATIBILITY_CONTEXT_ID",
        "CompatibilityState",
        "D4CompatibilityResult",
        "D4DerivationRecord",
        "D4Materialization",
        "D4SelectedSourceRecord",
        "LoopAssessmentContext",
        "LoopDecisionEvidenceBinding",
        "LoopExperimentOption",
        "LoopPhysicsScope",
        "MATERIALIZATION_SEMANTICS_ID",
        "NextExperimentDecision",
        "RECOMBINATION_OPERATOR",
        "SLOT_SCHEMA_ID",
        "D7Checkpoint",
        "assess_compatibility",
        "build_parent_candidates_and_memory",
        "child_candidate_id",
        "compare_child_to_parents",
        "d4_design_space",
        "materialize_recombination",
        "objective_plain",
        "preregistered_cases",
        "recombination_event_digest",
        "recombination_event_identity",
        "recombination_event_payload",
        "run_preregistered_case",
        "selected_parent_ids",
        "source_record",
        "synthetic_objective_values",
        "target_assessment",
        "typed_assignments",
        "validate_child_scientific_independence",
        "validate_no_inheritance",
    }
)


__all__ = ["PUBLIC_V1_MANIFEST"]
